### ISSUE TITLE
Example page not found

### ISSUE THREAD

**Issue by batoreh** [willianjusten/react-full-header#1]
https://willianjusten.com.br/react-full-header is returning 404

**Comment by willianjusten** [comment]
It's working by now. I just forgot to run `npm run deploy-storybook`.
I'll add a trigger to `travis` to do this always after tests.

**Comment by willianjusten** [comment]
Btw, this repository is just for study purposes, which one I use in my JS with TDD course.

**Comment by batoreh** [comment]
Okay, np. :)
